name: Create Secret in New Repository

on:
  repository_dispatch:
    types: [new-repository-created]  # Custom event type to trigger workflow

jobs:
  create-secret:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Node.js (for scripting)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install axios  # For API requests

    - name: Trigger Power Automate Flow to Create Secret
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.POWER_AUTOMATE_TOKEN }}" \
          -d '{
            "repository_name": "${{ github.repository }}",
            "secret_name": "MY_SECRET_KEY",
            "secret_value": "YourSecretValue"
          }' \
          https://YOUR-POWER-AUTOMATE-FLOW-URL
